### ISSUE TITLE
[Solved] Can't compile on Ubuntu Gnome 14.04 64 bit

### ISSUE THREAD

**Issue by htomeload** [stepmania/stepmania#1057]
I try many method to solve it like "check libc6-dev, libcrystalhd-dev and other installed" and "cmake -DWITH_CRYSTALHD_DISABLED=true -G 'Unix Makefiles' .. && cmake .. " but still got same error.

My PC
OS: Ubuntu Gnome 14.04 64 bit
Kernel version: 3.19.0-58-generic
CPU: Intel® Core™ i3-2120 CPU
GPU: AMD Radeon HD 6450
GPU driver: AMD Catalyst Display Driver 15.201.1151
GPU install method: Install by Additional Driver select option "Using Video driver for the AMD graphics accelerators from fglrx-updates (proprietary)"
Source code clone date: Fri., April 1 2016 01:18:44

> [  1%] Built target ffmpeg
> [  1%] Built target glew
> [  2%] Built target jsoncpp
> [  6%] Built target lua-5.1
> [  8%] Built target png
> [ 27%] Built target tomcrypt
> [ 44%] Built target tommath
> [ 44%] Building CXX object src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:173:2: error: #error "No size limited sprintf function available. Aborting."
>  #error "No size limited sprintf function available. Aborting."
>   ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:183:2: error: #error "No case insensitive string comparison function available. Aborting."
>  #error "No case insensitive string comparison function available. Aborting."
>   ^
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float powf(float, float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:205:72: error: ‘pow’ was not declared in this scope
>  float powf( float x, float y ) { return float( pow(double(x), double(y)) ); }
>                                                                         ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float sqrtf(float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:211:54: error: ‘sqrt’ was not declared in this scope
>  float sqrtf( float x ) { return float( sqrt(double(x)) ); }
>                                                       ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float sinf(float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:217:52: error: ‘sin’ was not declared in this scope
>  float sinf( float x ) { return float( sin(double(x)) ); }
>                                                     ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float tanf(float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:223:52: error: ‘tan’ was not declared in this scope
>  float tanf( float x ) { return float( tan(double(x)) ); }
>                                                     ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float cosf(float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:229:51: error: ‘cos’ was not declared in this scope
>  float cosf( float x ){ return float( cos(double(x)) ); }
>                                                    ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float acosf(float)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:235:54: error: ‘acos’ was not declared in this scope
>  float acosf( float x ) { return float( acos(double(x)) ); }
>                                                       ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: In function ‘float strtof(const char*, char**)’:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:252:80: error: ‘strtod’ was not declared in this scope
>  inline float strtof( const char *s, char **se ) { return (float) strtod( s, se ); }
>                                                                                 ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp: At global scope:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:252:14: error: previous declaration of ‘float strtof(const char*, char**)’ with ‘C++’ linkage
>  inline float strtof( const char *s, char **se ) { return (float) strtod( s, se ); }
>               ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/stdlib.h:173:44: error: conflicts with new declaration with ‘C’ linkage
>         char **__restrict __endptr) __THROW __nonnull ((1));
>                                             ^
> /usr/include/stdlib.h:173:44: error: declaration of ‘float strtof(const char*, char**) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:252:14: error: from previous declaration ‘float strtof(const char*, char**)’
>  inline float strtof( const char *s, char **se ) { return (float) strtod( s, se ); }
>               ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:235:7: error: previous declaration of ‘float acosf(float)’ with ‘C++’ linkage
>  float acosf( float x ) { return float( acos(double(x)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:54:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (acos,, (_Mdouble_ __x));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:54:1: error: declaration of ‘float acosf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:235:7: error: from previous declaration ‘float acosf(float)’
>  float acosf( float x ) { return float( acos(double(x)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:229:7: error: previous declaration of ‘float cosf(float)’ with ‘C++’ linkage
>  float cosf( float x ){ return float( cos(double(x)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (cos,, (_Mdouble_ __x));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:1: error: declaration of ‘float cosf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:229:7: error: from previous declaration ‘float cosf(float)’
>  float cosf( float x ){ return float( cos(double(x)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:217:7: error: previous declaration of ‘float sinf(float)’ with ‘C++’ linkage
>  float sinf( float x ) { return float( sin(double(x)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (sin,, (_Mdouble_ __x));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:1: error: declaration of ‘float sinf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:217:7: error: from previous declaration ‘float sinf(float)’
>  float sinf( float x ) { return float( sin(double(x)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:223:7: error: previous declaration of ‘float tanf(float)’ with ‘C++’ linkage
>  float tanf( float x ) { return float( tan(double(x)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:67:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (tan,, (_Mdouble_ __x));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:67:1: error: declaration of ‘float tanf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:223:7: error: from previous declaration ‘float tanf(float)’
>  float tanf( float x ) { return float( tan(double(x)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:205:7: error: previous declaration of ‘float powf(float, float)’ with ‘C++’ linkage
>  float powf( float x, float y ) { return float( pow(double(x), double(y)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (pow,, (_Mdouble_ __x, _Mdouble_ __y));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:1: error: declaration of ‘float powf(float, float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:205:7: error: from previous declaration ‘float powf(float, float)’
>  float powf( float x, float y ) { return float( pow(double(x), double(y)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:211:7: error: previous declaration of ‘float sqrtf(float)’ with ‘C++’ linkage
>  float sqrtf( float x ) { return float( sqrt(double(x)) ); }
>        ^
> In file included from /usr/include/features.h:374:0,
>                  from /usr/include/x86_64-linux-gnu/sys/types.h:25,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:194,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:156:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALL (sqrt,, (_Mdouble_ __x));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:156:1: error: declaration of ‘float sqrtf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:211:7: error: from previous declaration ‘float sqrtf(float)’
>  float sqrtf( float x ) { return float( sqrt(double(x)) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:247:7: error: previous declaration of ‘float roundf(float)’ with ‘C++’ linkage
>  float roundf( float f ) { if( f < 0.0f ) return truncf( f-0.5f ); return truncf( f+0.5f ); }
>        ^
> In file included from /usr/include/c++/4.8/cmath:44:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:153,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:309:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:309:1: error: declaration of ‘float roundf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:247:7: error: from previous declaration ‘float roundf(float)’
>  float roundf( float f ) { if( f < 0.0f ) return truncf( f-0.5f ); return truncf( f+0.5f ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:241:7: error: previous declaration of ‘float truncf(float)’ with ‘C++’ linkage
>  float truncf( float f ) { return float( int(f) ); }
>        ^
> In file included from /usr/include/c++/4.8/cmath:44:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:153,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:313:1: error: conflicts with new declaration with ‘C’ linkage
>  __MATHCALLX (trunc,, (_Mdouble_ __x), (__const__));
>  ^
> /usr/include/x86_64-linux-gnu/bits/mathcalls.h:313:1: error: declaration of ‘float truncf(float) throw ()’ has a different exception specifier
> In file included from /home/master/Games/StepMania-5.0.10/stepmania/src/global.h:5:0,
>                  from /home/master/Games/StepMania-5.0.10/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:1:
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:241:7: error: from previous declaration ‘float truncf(float)’
>  float truncf( float f ) { return float( int(f) ); }
>        ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:267:21: error: expected unqualified-id before ‘int’
>  #define lrintf(x) ((int)rint(x))
>                      ^
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:267:21: error: expected ‘)’ before ‘int’
> /home/master/Games/StepMania-5.0.10/stepmania/src/generated/config.hpp:267:21: error: expected ‘)’ before ‘int’
> make[2]: *** [src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o] Error 1
> make[1]: *** [src/CMakeFiles/GtkModule.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by kyzentun** [comment]
What version of gcc do you have installed?

**Comment by htomeload** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

**Comment by wolfman2000** [comment]
Make sure all of the packages mentioned in `.travis.yml` are installed (well, you don't need clang if you are using gcc). I'm trying to think what package you need for `snprintf`, however. Maybe build-essentials?

**Comment by htomeload** [comment]
I typing "sudo apt-get install build-essential" and it said I installed "build-essentials".

Maybe another package ? And sorry but what packages mentioned in .travis.yml ?

**Comment by htomeload** [comment]
On StepMania 5.1.0 Alpha 2. I can compile game now using 

> cmake -DWITH_CRYSTALHD_DISABLED=true -G 'Unix Makefiles' .. && cmake .. 

Then

> make

Thanks for all respond. Problem look like solved.
